### ISSUE TITLE
Feature request: just return next version

### ISSUE THREAD

**Issue by FixRM** [tunnckoCore/new-release#72]
Hello @tunnckoCore, I'm looking for a tool to calculate next version based on Conversational Commits. I want to use it not for node/js development but in CI pipeline. Is there any option to get number without any git/pakage.json manipulations?

**Comment by tunnckoCore** [comment]
Hi.

Try [`detect-next-version`](https://github.com/tunnckoCoreLabs/detect-next-version) package, it's exactly for that and is used here and in @standard-release.

**Comment by FixRM** [comment]
Hello,
Not really... I still need to detect last label, then get commits after that label and then pass them to `detect-next-version`. All together it's looking more like `new-release` without few lines of code but not like `detect-next-version` plus few lines.

I'm not lazy, I'm just not Node developer that's why I'm looking for existing solution :)

**Comment by tunnckoCore** [comment]
What's "last label"? :thinking: Sorry, I just don't get it. Elaborate more.

_(btw, closed it because it's not for here anyway, but for @standard-release or some of the other underlying libs)_

**Comment by FixRM** [comment]
I mean "tag". I found that similar tools first query for last SemVer looking tags like "v1.0.0" and only then query for commit messages that comes after that tag. For performance reasons, I believe.

Any way, we use Azure DevOps. Master branch is policy protected - no direct commits, only PRs are accepted. CI pipeline is set up but versions are given manually at the moment. CI handle all the things like build/test/publish/add tag. The problem is - there is no SemVer tools like yours available at the moment.

I believe I'll have to learn node and cook something on top of what's available :(

**Comment by tunnckoCore** [comment]
Oh, got it. There is [git-commits-since](https://github.com/tunnckoCoreLabs/git-commits-since) for that ;) Pass the `result.rawCommits` to `detect-next-version`.

Or basically, just use the [`@standard-release/cli`](https://github.com/standard-release/cli/blob/master/src/index.js#L6) as a module. It accepts the same options as the `git-commits-since` and `detect-next-version`. 

So I believe something like this would work

```js
const standardRelease = require('@standard-release/cli');

async function main() {
  const result = await standardRelease({ from: 'v1.1.0', cwd: '/home/foo/bar/qux' });
  
  // it basically returns the same result as `detect-next-version` 
  console.log(result);
}

main();
```

**Comment by FixRM** [comment]
Thanks a lot. It looks like there is still underling dependence of the version stored in package.json as I got Error: Cannot find module '@\\package.json'. But thanks for instructions anyway

**Comment by tunnckoCore** [comment]
Aaah, yea probably. Still, it's a strange error message, because it should be `@tunnckocore/package-json` at least.

Can you show the stack trace please. It depends on it to get the name, not the version which is in most cases more reliable than getting it from the path.

Edit: Actually, yea, we need the name because we request npm to get the lastest package.json data, from which we can get the lastest/current version and then pass it to `semver.inc` (to calculate needed bump, done in `recommended-bump` package)

**Comment by tunnckoCore** [comment]
Ah, I love how I'm building my things, so flexible and extendable... :heart_eyes: 
You can also pass `opts.packageJson` as a function which should return an object with `version` field. That's the only requirement.

The error is probably because of this https://github.com/standard-release/cli/blob/master/src/index.js#L14, which currently isn't possible to workaround but opened https://github.com/standard-release/cli/issues/5 for that.

<blockquote><img src="https://avatars1.githubusercontent.com/u/45472471?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/standard-release/cli">standard-release/cli</a></strong></div><div>Language independent module publishing, following Conventional Commits and SemVer, with support for monorepos. - standard-release/cli</div></blockquote>

**Comment by FixRM** [comment]
Thanks :)
